# -*- coding: utf-8 -*-
"""face_recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15zb8fGBRr53XN8Phfimn4h73TEWf1FM3
"""

# from google.colab import drive
# drive.mount('/content/drive')

import cv2, dlib, sys
import numpy as np

scaler = 0.3

detector = dlib.get_frontal_face_detector() # 얼굴 디텍터 모듈 초기화.
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat') # 얼굴 특징점 모듈 초기화. 머신러닝으로 이미 학습된 모델 파일을 사용함.

cap = cv2.VideoCapture('video.mp4') # video.mp4 동영상 파일 로드
# cv2.VideoCapture(0)_파일 경로대신 0을 넣으면 웹캠이 켜지고 웹캠으로 얼굴 인식 가능.

while True:
    ret, img = cap.read() # cap.read()_동영상 파일을 frame 단위로 읽기.
    if not ret:
        break

    img = cv2.resize(img, (int(img.shape[1] * scaler), int(img.shape[0] * scaler))) # cv2.resize(img, dsize)_img를 dsize 크기로 조절(resize)
    ori = img.copy()

    # detect faces
    faces = detector(img)
    face = faces[0] # 찾은 여러 얼굴이 있다면 첫번째 찾은 얼굴만 가져오기.

    dlib_shape = predictor(img, face) # img의 face 영역 안의 얼굴 특징점 찾기.
    shape_2d = np.array([[p.x, p.y] for p in dlib_shape.parts()]) # dlib 객체를 numpy 객체로 변환.

    # compute center and boundaries of face
    top_left = np.min(shape_2d, axis=0)
    bottom_right = np.max(shape_2d, axis=0)

    center_x, center_y = np.mean(shape_2d, axis=0).astype(np.int) # np.astype(np.int)_numpy행렬을 np.int타입으로 변환.

    # visualize
    img = cv2.rectangle(img, pt1=(face.left(), face.top()), pt2=(face.right(), face.bottom()), color=(255, 255, 255), thickness=2, lineType=cv2.LINE_AA) # pt1=좌상단, pt2=우하단
    # cv2.retangle()_직사각형 그리기.

    for s in shape_2d: # 68개의 얼굴 특징점을 for문에 cv2.cirlce을 사용하여 그리도록 함.
        cv2.circle(img, center=tuple(s), radius=1, color=(255, 255, 255), thickness=2, lineType=cv2.LINE_AA)

    cv2.circle(img, center=tuple(top_left), radius=1, color=(255, 0, 0), thickness=2, lineType=cv2.LINE_AA)
    cv2.circle(img, center=tuple(bottom_right), radius=1, color=(255, 0, 0), thickness=2, lineType=cv2.LINE_AA)

    cv2.circle(img, center=tuple((center_x, center_y)), radius=1, color=(0, 0, 255), thickness=2, lineType=cv2.LINE_AA)

    cv2.imshow('img', img) # 'img'라는 이름의 윈도우에 img 띄우기.
    cv2.waitKey(1) # 1ms의 시간만큼 대기. 동영상이 제대로 보이려면 필수.
